Removes the euro symbol to prevent encoding errors
When requesting a new code I got a unicode error:

UnicodeEncodeError: 'charmap' codec can't encode character '\u20ac' in position 133: character maps
to <undefined>

This is caused by the euro sign, this is a temporary fix until someone with more Python expierience comes along.