Only encode a string object, not a byte object
Since the recent changes, `serializedData` is passed in as a byte object and I see a lot of these errors, for each message:
`WARNING:yowsup.layers.axolotl.layer_receive:AttributeError: 'bytes' object has no attribute 'encode'. Skipping 'encode()'`

This adds a small check to only encode a string object, as a byte object does not have the encode() method.