[feat] handle errors processing fetched keys
Previously a successful fetch of a given jid's keys assumed the user
must be valid which had some unexpected outcome.
This change will check availability of all required data before
creating a prekey bundle, and will abort sending the message if there
is any reported errors.

At the moment errors might be MissingParameters or UntrustedIdentity of
autotrust is disabled.

It seems MissingParameters might be the case, where key/prekey is
missing, when the given username is valid format (looks like a phone
number), but does not exist, and this seems to be the cause of almost
all current relevant issues.

Fixed tests for ResultGetsKey

Fixes #2582 Error on sending simple message
Fixes #1363 Unable to send message to group
Fixes #1985 'NoneType' object has no attribute 'getChild'
Fixes #1521 AttributeError: 'NoneType' object has no attribute 'getChild'
Fixes #1085 Exception: iq result for key asking has not contains key token